/* This C header file is generated by NIT to compile modules and programs that requires /home/jp/Projects-ssd/nit//lib/standard/time. */
#ifndef standard___time_sep
#define standard___time_sep
#include "standard___kernel._sep.h"
#include <nit_common.h>
#include "time._nitni.h"
extern const char LOCATE_standard___time[];
extern const int SFT_standard___time[];
#define CALL_standard___time___Object___get_time(recv) ((standard___time___Object___get_time_t)CALL((recv), (SFT_standard___time[0] + 0)))
#define CALL_standard___time___Int___sleep(recv) ((standard___time___Int___sleep_t)CALL((recv), (SFT_standard___time[1] + 0)))
#define CALL_standard___time___Int___nanosleep(recv) ((standard___time___Int___nanosleep_t)CALL((recv), (SFT_standard___time[1] + 1)))
val_t standard___time___Object___get_time(val_t p0);
typedef val_t (*standard___time___Object___get_time_t)(val_t p0);
void standard___time___Int___sleep(val_t p0);
typedef void (*standard___time___Int___sleep_t)(val_t p0);
void standard___time___Int___nanosleep(val_t p0);
typedef void (*standard___time___Int___nanosleep_t)(val_t p0);
#endif
