/* This C file is generated by NIT to compile module test. */
#include "test._sep.h"
static const char LOCATE_test___ConnectionListener___read_callback[] = "test::ConnectionListener::(event::ConnectionListener::read_callback)";
void test___ConnectionListener___read_callback(val_t p0){
  struct {struct stack_frame_t me; val_t MORE_REG[1];} fra;
  val_t REGB0;
  val_t tmp;
  static val_t once_value_1; /* Once value */
  fra.me.prev = stack_frame_head; stack_frame_head = &fra.me;
  fra.me.file = LOCATE_test;
  fra.me.line = 3;
  fra.me.meth = LOCATE_test___ConnectionListener___read_callback;
  fra.me.has_broke = 0;
  fra.me.REG_size = 2;
  fra.me.nitni_local_ref_head = NULL;
  fra.me.REG[0] = NIT_NULL;
  fra.me.REG[1] = NIT_NULL;
  fra.me.REG[0] = p0;
  /* test.nit:4 */
  if (!once_value_1) {
    fra.me.REG[1] = BOX_NativeString("Hello");
    REGB0 = TAG_Int(5);
    fra.me.REG[1] = NEW_String_standard___string___String___with_native(fra.me.REG[1], REGB0);
    once_value_1 = fra.me.REG[1];
    register_static_object(&once_value_1);
  } else fra.me.REG[1] = once_value_1;
  fra.me.REG[1] = fra.me.REG[1];
  CALL_standard___file___Object___print(fra.me.REG[0])(fra.me.REG[0], fra.me.REG[1]);
  stack_frame_head = fra.me.prev;
  return;
}
