/* This C header file is generated by NIT to compile modules and programs that requires ./test. */
#ifndef test_sep
#define test_sep
#include "event._sep.h"
#include <nit_common.h>
extern const char LOCATE_test[];
extern const int SFT_test[];
void test___ConnectionListener___read_callback(val_t p0);
typedef void (*test___ConnectionListener___read_callback_t)(val_t p0);
val_t NEW_ConnectionListener_event___ConnectionListener___bind_to(val_t p0, val_t p1, val_t p2);
#endif
